import type { Resume } from "../src/lib/types.ts";

export const resume: Resume = {
  meta: { id: "x", name: "test", type: "chronological", createdAt: "", updatedAt: "" },
  target: { jobDescription: "", enabled: false },
  contact: {
    fullName: "Bilal Ahmed",
    title: "Senior Software Engineer",
    phone: "+92 300 1234567",
    email: "bilal.ahmed@example.com",
    city: "Lahore",
    country: "Pakistan",
    linkedin: "linkedin.com/in/bilal-ahmed",
    website: "",
    github: "github.com/bilalahmed",
    portfolioUrl: "",
  },
  summary: "Results-driven full-stack engineer with 6 years of experience building web applications and leading teams.",
  objective: "",
  useObjective: false,
  experience: [
    {
      id: "j1",
      company: "TechNova Solutions",
      role: "Senior Software Engineer",
      location: "Lahore",
      startDate: "01/2021",
      endDate: "05/2024",
      present: false,
      descriptor: "",
      bullets: [
        "Led a team of 5 engineers to deliver a payments platform used by 2M users.",
        "Built REST APIs in Node.js that cut response time by 40%.",
        "Introduced CI/CD pipelines reducing release time from days to hours.",
      ],
    },
    {
      id: "j2",
      company: "ByteWorks",
      role: "Software Engineer",
      location: "Islamabad",
      startDate: "06/2018",
      endDate: "12/2020",
      present: false,
      descriptor: "",
      bullets: ["Developed front-end features in React for a healthcare dashboard."],
    },
    {
      id: "j3",
      company: "SoftMart",
      role: "Junior Developer",
      location: "Karachi",
      startDate: "2017",
      endDate: "2018",
      present: false,
      descriptor: "",
      bullets: ["Maintained internal tools and fixed 100+ bugs."],
    },
  ],
  education: [
    {
      id: "e1",
      institution: "National University of Sciences & Technology",
      degree: "Bachelor of Science",
      field: "Computer Science",
      location: "Islamabad",
      startDate: "2014",
      endDate: "2018",
      gpa: "3.7",
      honors: "",
      coursework: "Data Structures, Algorithms, Operating Systems",
      thesis: "",
    },
  ],
  skills: [
    { id: "s1", name: "Programming Languages", skills: ["JavaScript", "TypeScript", "Python"] },
    { id: "s2", name: "", skills: ["React", "Node.js", "PostgreSQL"] },
  ],
  projects: [],
  certifications: [{ id: "c1", name: "AWS Certified Developer", issuer: "Amazon", year: "2022", expires: "" }],
  languages: [{ id: "l1", name: "English", level: "Fluent" }],
  volunteer: [],
  publications: [],
  awards: [],
  teaching: [],
  grants: [],
  presentations: [],
  affiliations: [],
  references: [{ id: "r1", name: "John Doe", title: "Manager", org: "TechNova", email: "", phone: "" }],
  sectionOrder: [],
  visibility: {} as Resume["visibility"],
  theme: { template: "classic", accent: "#1d2130", fontPair: "a", density: "compact", atsSafe: true, pageSize: "a4", maxPages: 1, citationFormat: "apa" },
};
